"""Adicionados modelos User e Task.

Revision ID: 9b7c52e673b1
Revises: 8e83d258b542
Create Date: 2024-09-25 09:47:44.775681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b7c52e673b1'
down_revision: Union[str, None] = '8e83d258b542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
